/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cleimer
 */
public class FrmProductoFresco extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductoFresco
     */
    public FrmProductoFresco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnGuardarPF = new javax.swing.JButton();
        jBtnLimpiarPF = new javax.swing.JButton();
        jBtnSalirPF = new javax.swing.JButton();
        jTxtNombrePF = new javax.swing.JTextField();
        jTxtCaducidadPF = new javax.swing.JTextField();
        jTxtLotePF = new javax.swing.JTextField();
        jTxtEnvasadoPF = new javax.swing.JTextField();
        jTxtPaisPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtResultadoPF = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Fecha de Caducidad:");

        jLabel3.setText("N° de Lote:");

        jLabel4.setText("Fecha de Envasado:");

        jLabel5.setText("País de Origen:");

        jBtnGuardarPF.setText("GUARDAR");
        jBtnGuardarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarPFActionPerformed(evt);
            }
        });

        jBtnLimpiarPF.setText("LIMPIAR");
        jBtnLimpiarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarPFActionPerformed(evt);
            }
        });

        jBtnSalirPF.setText("SALIR");
        jBtnSalirPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirPFActionPerformed(evt);
            }
        });

        jTxtResultadoPF.setColumns(20);
        jTxtResultadoPF.setRows(5);
        jScrollPane1.setViewportView(jTxtResultadoPF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBtnGuardarPF)
                        .addGap(36, 36, 36)
                        .addComponent(jBtnLimpiarPF)
                        .addGap(55, 55, 55)
                        .addComponent(jBtnSalirPF))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNombrePF)
                            .addComponent(jTxtCaducidadPF)
                            .addComponent(jTxtLotePF)
                            .addComponent(jTxtEnvasadoPF)
                            .addComponent(jTxtPaisPF, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNombrePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtCaducidadPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtLotePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtEnvasadoPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtPaisPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardarPF)
                    .addComponent(jBtnLimpiarPF)
                    .addComponent(jBtnSalirPF))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLimpiarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarPFActionPerformed
        // TODO add your handling code here:
        jTxtNombrePF.setText("");
        jTxtCaducidadPF.setText("");
        jTxtLotePF.setText("");
        jTxtEnvasadoPF.setText("");
        jTxtPaisPF.setText("");
        jTxtResultadoPF.setText("");
    }//GEN-LAST:event_jBtnLimpiarPFActionPerformed

    private void jBtnSalirPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirPFActionPerformed
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_jBtnSalirPFActionPerformed

    private void jBtnGuardarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarPFActionPerformed
        // TODO add your handling code here:
        String nombre = jTxtNombrePF.getText();
        String fechaCaducidad = jTxtCaducidadPF.getText();
        int numeroLote = Integer.parseInt(jTxtLotePF.getText());
        String fechaEnvasado = jTxtEnvasadoPF.getText();
        String paisOrigen = jTxtPaisPF.getText();
        
        ProductoFresco pf = new ProductoFresco(nombre, fechaCaducidad, numeroLote, fechaEnvasado, paisOrigen);
        
        jTxtResultadoPF.setText(pf.mostrarDatosPF());
    }//GEN-LAST:event_jBtnGuardarPFActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductoFresco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductoFresco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductoFresco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductoFresco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductoFresco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardarPF;
    private javax.swing.JButton jBtnLimpiarPF;
    private javax.swing.JButton jBtnSalirPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCaducidadPF;
    private javax.swing.JTextField jTxtEnvasadoPF;
    private javax.swing.JTextField jTxtLotePF;
    private javax.swing.JTextField jTxtNombrePF;
    private javax.swing.JTextField jTxtPaisPF;
    private javax.swing.JTextArea jTxtResultadoPF;
    // End of variables declaration//GEN-END:variables
}
