/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cleimer
 */
public class Herencia extends javax.swing.JFrame {

    /**
     * Creates new form Herencia
     */
    public Herencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemPC = new javax.swing.JMenuItem();
        jMenuItemPF = new javax.swing.JMenuItem();
        jMenuItemPR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Productos");

        jMenuItemPC.setText("Producto Congelado");
        jMenuItemPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPCActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPC);

        jMenuItemPF.setText("Producto Fresco");
        jMenuItemPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPFActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPF);

        jMenuItemPR.setText("Producto Refrigerado");
        jMenuItemPR.setToolTipText("");
        jMenuItemPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPRActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPR);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPCActionPerformed
        // TODO add your handling code here:
        FrmProductoCongelado fm = new FrmProductoCongelado();
        fm.show();
    }//GEN-LAST:event_jMenuItemPCActionPerformed

    private void jMenuItemPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPFActionPerformed
        // TODO add your handling code here:
        FrmProductoFresco fm = new FrmProductoFresco();
        fm.show();
    }//GEN-LAST:event_jMenuItemPFActionPerformed

    private void jMenuItemPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPRActionPerformed
        // TODO add your handling code here:
        FrmProductoRefrigerado fm = new FrmProductoRefrigerado();
        fm.show();
    }//GEN-LAST:event_jMenuItemPRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Herencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPC;
    private javax.swing.JMenuItem jMenuItemPF;
    private javax.swing.JMenuItem jMenuItemPR;
    // End of variables declaration//GEN-END:variables
}
